version: "3.9"

services:
  app:
    build:
      context: .
      target: demo-spring-boot-api-simple-development
      # dockerfile: Dockerfile
      # network: host
    environment:
      MAVEN_CONFIG: /root/.m2
      SERVER_PORT: 80
      SPRING_PROFILES_ACTIVE: dev # local
    expose:
      - 80
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    ports:
      - 80:80
    tty: true
    volumes:
      - ./:/usr/src/app
      - ${HOME}/.m2/repository:/root/.m2/repository

  playwright:
    image: node:18.15.0
    working_dir: /home/node/app
    # environment:
    #   KEY: value
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    command: npm run test-e2e
    volumes:
      - ./playwright/:/home/node/app
