name: Playwright Tests

on:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          docker-compose pull
          docker-compose build
      - name: Run tests
        run: |
          docker-compose up -d app & sleep 20
          docker-compose up playwright
